Repository bigcommerce/api-specs, pull requests merged in 2022-03, with the labels that each got.

#637 DEVDOCS-3557 fix(shipping): SHIPPING-700 Update Customs Info API docs
  reference/shipping.v3.yml
Labels: awaiting-final-review

#640 Devdocs 3579 no quote format
  reference/shipping_provider.yml
Labels: awaiting-final-review

#639 Devdocs 3576 blog reference
  reference/store_content.v2.yml
Labels: awaiting-final-review

#671 DEVDOCS-3628-correct-documentation
  reference/customers.v3.yml
  reference/orders.v3.yml
Labels: dependencies

#644 DEVDOCS-3441 Update orders.v2.oas2.yml
  reference/orders.v2.oas2.yml
Labels: awaiting-final-review

#682 Update `origin_channel_ID` throughout CustomersV3
  reference/customers.v3.yml
Labels: ready-to-merge

#606 Update orders.v2.oas2.yml
  reference/orders.v2.oas2.yml
Labels: awaiting-final-review

#686 Tag `refunded_amount` as deprecated
  reference/orders.v2.oas2.yml
Labels: ready for review

#692 Devdocs 3435
  reference/customers.v3.yml
Labels: ready for review
