Repository bigcommerce/api-specs, pull requests merged in 2022-12, with the labels that each got.

#1063 DEVDOCS-4480: [fix] Marketing, convert dates to RFC 2822
  reference/marketing.v2.yml
Labels: ready-to-merge, awaiting-final-review

#1074 DEVDOCS-3814: [update] Add Batch Limit to Get Price List Assignments
  reference/price_lists.v3.yml
Labels: awaiting-final-review

#1079 DEVDOCS-4653: [fix] Geography endpoint path
  reference/geography.v2.yml
Labels: awaiting-final-review, awaiting-peer-review

#1080 DEVDOCS-4654: [fix] Widgets endpoint path
  reference/widgets.v3.yml
Labels: awaiting-final-review

#1072 fixed wrong field names in v3/catalog/product
  reference/catalog.v3.yml
Labels: external, awaiting-final-review, awaiting-peer-review
