Repository bigcommerce/api-specs, pull requests merged in 2022-06, with the labels that each got.

#740 DEVDOCS-3803-update-payment-docs
  reference/checkouts.v3.yml
  reference/payment_processing.yml
Labels: do not merge, awaiting-pe-sme-review, awaiting-peer-review

#799 DEVDOCS-4182: Orders v3 YAML file is malformed
  reference/orders.v3.yml
Labels: external

#802 DEVDOCS-4183: V2 store content Blog POST and PUT payloads have incorrect published date format
  reference/store_content.v2.yml
Labels: external, awaiting-final-review, awaiting-peer-review

#803 DEVDOCS-4184: v3 order refunds POST and refunds quote POST request bodies do not resolve items field correctly
  reference/orders.v3.yml
Labels: external, awaiting-pe-sme-review, awaiting-final-review, awaiting-peer-review

#804 DEVDOCS-4185: v3 catalog PUT products should not enforce mandatory fields, but POST should
  reference/catalog.v3.yml
Labels: external, awaiting-pe-sme-review, awaiting-final-review, awaiting-peer-review

#812 DEVDOCS 3716
  reference/orders.v3.yml
Labels: ready-to-merge, awaiting-final-review

#815 Correct Metafields example Orders v3
  reference/orders.v3.yml
Labels: ready-to-merge, awaiting-final-review

#846 Devdocs 3800
  reference/orders.v2.oas2.yml
Labels: awaiting-peer-review

#856 Staging to Master
  reference/orders.v3.yml
  reference/redirects.v3.yml
Labels: silent
