Repository bigcommerce/api-specs, pull requests merged in 2022-05, with the labels that each got.

#536 docs(tax): DEVDOCS-3835 Add tax properties array to item requests
  reference/tax_provider.yml
Labels: engineering

#757 DEVDOCS-3884-increase-limits-to-250
  reference/catalog.v3.yml
  reference/orders.v3.yml
Labels: ready for review, awaiting-pe-sme-review, awaiting-final-review, awaiting-peer-review

#760 DEVDOCS-3920-update-available-shipping-array
  reference/checkouts.v3.yml
Labels: awaiting-final-review

#752 DEVDOCS-3889: Updated-oauth-scopes
  reference/abandoned_carts.v3.yml
Labels: awaiting-final-review

#755 DEVDOCS-3894-removed-X-Auth-Token-from-process-payment-endpoint
  reference/payment_processing.yml
Labels: awaiting-final-review

#730 DEVDOCS-3781: add-webdav-example
  reference/checkouts.v3.yml
Labels: do not merge, awaiting-css-cue

#750 DEVDOCS-3881: fix(customers): CUST-2101 Adding form field schema to address under C…
  reference/customers.v3.yml
Labels: ready-to-merge

#771 DEVDOCS-3668: Modified reference/catalog.v3.yml
  reference/catalog.v3.yml
Labels: awaiting-peer-review

#737 DEVDOCS-3729 - find and replace $$.env.store_hash with store_hash
  models/webhooks/webhooks_events.yml
  reference/abandoned_cart_emails.v3.yaml
  reference/abandoned_carts.v3.yml
  reference/carts.v3.yml
  reference/catalog.v3.yml
  reference/channels.v3.yml
  reference/checkouts.v3.yml
  reference/custom-template-associations.v3.yml
  reference/customers.v2.yml
  reference/customers.v3.yml
  reference/email_templates.v3.yml
  reference/geography.v2.yml
  reference/orders.v2.oas2.yml
  reference/payment_methods.v2.yml
  reference/payment_processing.yml
  reference/price_lists.v3.yml
  reference/redirects.v3.yml
  reference/scripts.v3.yml
  reference/shipping.v2.yml
  reference/shipping.v3.yml
  reference/store_content.v2.yml
  reference/store_information.v2.yml
  reference/storefront_tokens.v3.yml
  reference/subscribers.v3.yml
  reference/tax.v3.yml
  reference/tax_classes.v2.yml
  reference/themes.v3.yml
  reference/widgets.v3.yml
  reference/wishlists.v3.yml
Labels: ready-to-merge

#775 DEVDOCS-3758: Remove X-Auth-Client headers
  reference/currencies.v2.yml
  reference/customers.v2.yml
  reference/marketing.v2.yml
  reference/orders.v2.oas2.yml
  reference/redirects.v3.yml
  reference/scripts.v3.yml
  reference/shipping.v2.yml
  reference/shipping.v3.yml
  reference/store_content.v2.yml
  reference/store_information.v2.yml
  reference/storefront_tokens.v3.yml
  reference/subscribers.v3.yml
  reference/tax_classes.v2.yml
  reference/themes.v3.yml
  reference/wishlists.v3.yml
Labels: awaiting-final-review

#784 DEVDOCS-3934: Rebrand Facebook
  reference/channels.v3.yml
  reference/orders.v2.oas2.yml
  reference/store_content.v2.yml
  reference/store_information.v2.yml
Labels: awaiting-final-review

#792 DEVDOCS-4110-remove-response-body
  reference/carts.sf.yml
Labels: awaiting-final-review

#797 Update-create-a-product-modifier-endpoint
  reference/catalog.v3.yml
Labels: awaiting-final-review, awaiting-peer-review
