Repository bigcommerce/api-specs, pull requests merged in 2022-07, with the labels that each got.

#862 DEVDOCS-3950: Converting to OAS3
  reference/current_customer.yml
Labels: awaiting-final-review

#877 DEVDOCS-4224 add bigcommerce platform to the list of storefront channel types
  reference/channels.v3.yml
Labels: awaiting-peer-review

#870 DEVDOCS-4306-Update current_customer.yml
  reference/current_customer.yml
Labels: awaiting-final-review, awaiting-peer-review
