Repository bigcommerce/api-specs, pull requests merged in 2022-09, with the labels that each got.

#944 DEVDOCS-4338: [edit] Sites API typos
  reference/sites.v3.yml
Labels: ready-to-merge

#964 DEVDOCS-4426: [maintenance] Abandoned Cart email template, add product id
  models/email_templates/abandoned_cart_email.yml
Labels: awaiting-peer-review

#955 (no ticket): [maintenance] Carts V3 API, improve schemas, descriptions, linting
  reference/carts.v3.yml
Labels: awaiting-creator-rereview

#975 DEVDOCS-4483: [update description] Tax Provider, ItemRequest item_code
  reference/tax_provider.yml
Labels: awaiting-final-review

#977 DEVDOCS-4483: [maintenance] Adjust Tax Provider ItemRequest Item Code description
  reference/tax_provider.yml
Labels: awaiting-final-review

#978 DEVDOCS-4488: [maintenance] Include tax properties on ItemRequest
  reference/tax_provider.yml
Labels: awaiting-final-review

#948 DEVDOCS-4377: [new] Orders V3, Create a refund, add 422 response
  reference/orders.v3.yml
Labels: ready-to-merge

#961 DEVDOCS-4339: [maintenance] Price Lists, update MAP definition
  reference/price_lists.v3.yml
Labels: ready-to-merge, awaiting-final-review
