Repository bigcommerce/api-specs, pull requests merged in 2022-08, with the labels that each got.

#849 DEVDOCS-4246 Create an Order Request Body Cleanup
  reference/orders.v2.oas2.yml
Labels: ready-to-merge

#919 DEVDOCS-4184: [edit] Fix the request body schema for creating refunds
  reference/orders.v3.yml
Labels: ready-to-merge, awaiting-final-review

#915 DEVDOCS-4371: [edit] Add gift certificate ID to Orders v2
  reference/orders.v2.oas2.yml
Labels: awaiting-css-cue, spectral-updated

#940 DEVDOCS-4392 Orders V2 [Maintenance] Fix broken links to tracking_carrier list
  reference/orders.v2.oas2.yml
Labels: awaiting-peer-review

#916 DEVDOCS-4342: [remove] Remove references to Facebook Marketplace
  reference/channels.v3.yml
Labels: spectral-updated

#918 DEVDOCS-4360: [remove] Remove request body for Get accepted payment methods
  reference/payment_processing.yml
Labels: spectral-updated

#917 DEVDOCS-4350: [edit] Add custom template association reference
  reference/catalog.v3.yml
  reference/store_content.v2.yml
Labels: spectral-updated

#909 DEVDOCS-4310: [update] Update parameter type for reviews_rating_sum
  reference/catalog.v3.yml
Labels: awaiting-final-review, spectral-updated

#943 chore(customers): (Customer Segmentation) CUST-1745 add includes for segments (#895)
  reference/customers.v3.yml
Labels: awaiting-peer-review
