Repository bigcommerce/api-specs, pull requests merged in 2022-11, with the labels that each got.

#1036 DEVDOCS-4529: [remove] Duplicate outdated version of webhook_events spec
  models/webhooks/webhooks_events.yml
Labels: awaiting-final-review

#1029 Devdocs 4553 update timestamp format
  reference/catalog.v3.yml
  reference/sites.v3.yml
Labels: awaiting-pe-sme-review

#1007 DEVDOCS-4464: [edit] Settings v3, modify storefront product response
  reference/settings.v3.yml
Labels: awaiting-code-owner

#1043 DEVDOCS-4568: [update] Remove negative numbers
  reference/catalog.v3.yml
  reference/customers.v3.yml
  reference/shipping.v2.yml
  reference/store_content.v2.yml
  reference/store_information.v2.yml
Labels: in-editorial-review

#1044 DEVDOCS-3878: [maintenance] price list assignments
  reference/price_lists.v3.yml
Labels: awaiting-final-review

#1053 DEVDOCS-4604: [update] Remove beta label from List Stored Instruments
  reference/customers.v3.yml
Labels: ready-to-merge

#1056 DEVDOCS-4605: [update] Payments, add bigpay_token
  reference/orders.v3.yml
Labels: do not merge, awaiting-pe-sme-review, awaiting-css-cue
