Repository bigcommerce/api-specs, pull requests merged in 2022-04, with the labels that each got.

#701 DEVDOCS-3705-add-checkout_id
  reference/payment_processing.yml
Labels: awaiting-final-review, awaiting-peer-review

#710 DEVDOCS-3302?: docs(checkout): CHECKOUT-6553 Add documentation for storefront cart currency endpoint
  reference/carts.sf.yml
Labels: awaiting-creator-rereview, caution-force-push

#699 chore(customers): CUST-1945 update address schema for create customers
  reference/customers.v3.yml
Labels: do not merge, caution-force-push, awaiting-css-cue

#711 DEVDOCS-3717-update-response
  reference/carts.v3.yml
Labels: awaiting-creator-rereview, awaiting-final-review

#724 DEVDOCS-3730-removed-keyword-like
  reference/catalog.v3.yml
Labels: ready for review, awaiting-final-review, awaiting-peer-review

#722 DEVDOCS-3786: fix payment processing paths
  reference/payment_processing.yml
Labels: awaiting-peer-review

#727 DEVDOCS-3302-fixed-editorial-error
  reference/carts.sf.yml
Labels: ready for review, awaiting-final-review

#728 Fixed-file-errors
  reference/catalog.v3.yml
Labels: ready for review, awaiting-final-review

#725 DEVDOCS-3718-add-text
  reference/catalog.v3.yml
Labels: ready-to-merge, awaiting-final-review

#723 Devdocs 3784 add value to list
  reference/catalog.v3.yml
Labels: ready-to-merge, awaiting-final-review

#729 Staging into master
  reference/carts.sf.yml
  reference/catalog.v3.yml
Labels: do not merge

#712 DEVDOCS-3778: fix(customers): CUST-2064 Remove customer_id from update address
  reference/customers.v3.yml
Labels: awaiting-css-cue, awaiting-peer-review

#739 DEVDOCS-3836: change-shipping-address-to-address
  reference/checkouts.sf.yml
Labels: ready-to-merge

#732 DEVDOCS-3762: add-discount-to-checkout
  reference/checkouts.v3.yml
Labels: ready-to-merge

#736 DEVDOCS-3670: broken image on graphql page
  docs/storefront-graphql.md
Labels: ready-to-merge

#751 DEVDOCS-3873-add-clarification-to-process-payment-endpoint
  reference/payment_processing.yml
Labels: ready for review, awaiting-pe-sme-review, awaiting-final-review, awaiting-peer-review

#731 DEVDOCS-3643: Checkout domain per headless storefront
  reference/channels.v3.yml
  reference/sites.v3.yml
Labels: awaiting-creator-rereview
