Repository bigcommerce/api-specs, pull requests merged in 2023-05, with the labels that each got.

#1284 DEVDOCS-4899: [revise] Payments, clarify API features
  reference/payments/accepted-methods_payments.v3.yml
  reference/payments/access-tokens_payments.v3.yml
  reference/payments/methods_payments.v2.yml
  reference/payments/process_payments.yml
Labels: awaiting-final-review

#1294 DEVDOCS-4931: [update] Tax Connection API, edit 404 error message
  reference/tax.v3.yml
Labels: awaiting-devdocs-sme

#1292 DEVDOCS-4916: [revise] Ordersv3 - payment-field is an array
  reference/orders.v3.yml
Labels: ready-to-merge

#1303 updated per DEVDOCS-4928
  models/email_templates/_all.yml
Labels: ready-to-merge

#1302 DEVDOCS-4896: [update] add unshipped_products
  models/email_templates/_all.yml
Labels: ready-to-merge

#1309 Removed required for the headers field
  reference/webhooks.v3.yml
Labels: ready-to-merge

#1323 DEVDOCS-4355: Ordersv2 - Order products, update header
  reference/orders.v2.oas2.yml
Labels: awaiting-peer-review

#1325 DEVDOCS-4555: [revise] OrdersV2, Create an Order schema cleanup
  reference/orders.v2.oas2.yml
Labels: awaiting-peer-review

#1327 DEVDOCS-4405: [update] category-trees_catalog.v3.yml
  reference/catalog/category-trees_catalog.v3.yml
Labels: ready-to-merge, awaiting-final-review

#1329 DEVDOCS-3901: [update] clarify create a product video endpoint
  reference/catalog/products_catalog.v3.yml
Labels: awaiting-peer-review

#1328 DEVDOCS-4190: [update] complex-rules endpoint
  reference/catalog/products_catalog.v3.yml
Labels: awaiting-peer-review

#1324 DEVDOCS-4891: [new] Catalog API, add handling for inventory limits
  reference/catalog/product-variants_catalog.v3.yml
  reference/catalog/products_catalog.v3.yml
Labels: awaiting-peer-review
