Repository bigcommerce/api-specs, pull requests merged in 2023-03, with the labels that each got.

#1163 DEVDOCS-4719: [migrate] Catalog V3, fix request body not rendering
  reference/catalog.v3.yml
Labels: awaiting-final-review

#1166 DEVDOCS-4719: [migrate] Catalog V3, rendering issues
  reference/catalog.v3.yml
Labels: awaiting-final-review

#1174 DEVDOCS-4719: [migrate] Many, update additionalProperties
  reference/settings.v3.yml
  reference/sites.v3.yml
  reference/subscribers.v3.yml
  reference/themes.v3.yml
  reference/widgets.v3.yml
Labels: ready for review, awaiting-final-review

#1187 DEVDOCS-4719: [migrate] Price Lists V3 API, remove content type header from GET
  reference/price_lists.v3.yml
Labels: awaiting-final-review

#1185 DEVDOCS-4719 [migrate] Orders, summary/table cleanup
  reference/orders.v2.oas2.yml
Labels: awaiting-final-review

#1183 DEVDOCS-4719: [migrate] Tax V3 API, rendering
  reference/tax.v3.yml
Labels: awaiting-final-review

#1194 DEVDOCS-4719: [migrate] Shipping provider API, move example
  reference/shipping_provider.yml
Labels: awaiting-final-review

#1125 DEVDOCS-4633: [revise] Storefront Customers, update schema
  reference/catalog.v3.yml
  reference/customers.sf.yml
Labels: awaiting-final-review

#1126 DEVDOCS-4693: [update] Get all states, add query parameters
  reference/geography.v2.yml
Labels: awaiting-final-review

#1139 DEVDOCS-4766:[update] Pages v3, add url in the response
  reference/pages.v3.yml
Labels: awaiting-final-review

#1108 DEVDOCS-4684: [update] Catalog, revise bulk pricing rule amount definition
  reference/catalog.v3.yml
Labels: awaiting-creator-rereview

#1124 DEVDOCS-3987: [update] Orders V3; Get refund quote, update items array
  reference/orders.v3.yml
Labels: awaiting-final-review

#1060 DEVDOCS-4429: [value add] Carts, add locale examples
  reference/carts.v3.yml
Labels: awaiting-final-review
