Repository bigcommerce/api-specs, pull requests merged in 2023-06, with the labels that each got.

#1340 DEVDOCS-5037: [updates] Many, add references to GraphQL Storefront carts & checkout
  reference/abandoned_carts.v3.yml
  reference/carts.sf.yml
  reference/carts.v3.yml
  reference/catalog/categories_catalog.v3.yml
  reference/catalog/products_catalog.v3.yml
  reference/checkouts.sf.yml
  reference/custom-template-associations.v3.yml
  reference/customers.sf.yml
  reference/payments/access-tokens_payments.v3.yml
  reference/payments/process_payments.yml
  reference/storefront_tokens.v3.yml
  reference/tax_provider.yml
  reference/webhooks.v3.yml
  reference/widgets.v3.yml
Labels: do not merge

#1339 DEVDOCS-4525: [revise] Webhooks, update descriptions for product/sku
  models/webhooks/_all.yml
  models/webhooks/store_product_inventory_order_updated.yml
  models/webhooks/store_product_inventory_updated.yml
  models/webhooks/store_sku_inventory_order_updated.yml
  models/webhooks/store_sku_inventory_updated.yml
Labels: awaiting-pe-sme-review

#1318 DEVDOCS-4936: [update] Add callbacks for metafields
  models/webhooks/_all.yml
  models/webhooks/data/store_metafield_created.json
  models/webhooks/store_inventory_location_created.yml
  models/webhooks/store_inventory_location_updated.yml
  models/webhooks/store_metafield_created.yml
  models/webhooks/store_metafield_deleted.yml
  models/webhooks/store_metafield_updated.yml
  models/webhooks/store_order_metafield_created.yml
  models/webhooks/store_order_metafield_deleted.yml
  models/webhooks/store_order_metafield_updated.yml
  models/webhooks/store_product_metafield_created.yml
  models/webhooks/store_product_metafield_deleted.yml
  models/webhooks/store_product_metafield_updated.yml
  models/webhooks/store_variant_metafield_created.yml
  models/webhooks/store_variant_metafield_deleted.yml
  models/webhooks/store_variant_metafield_updated.yml
Labels: awaiting-peer-review

#1342 DEVDOCS-4619: [revise] OrdersV2, payment method description
  reference/orders.v2.oas2.yml
Labels: awaiting-peer-review

#1348 DEVDOCS-4461: [update] Update character minimum length for `description`
  reference/catalog/product-variants_catalog.v3.yml
Labels: awaiting-peer-review

#1354 DEVDOCS-4753: [revise] Price lists, webhook changes
  reference/price_lists.v3.yml
Labels: awaiting-peer-review

#1357 DEVDOCS-4922: [revise] Add-missing-callbacks
  models/webhooks/_all.yml
  models/webhooks/store_order_transaction_created.yml
  models/webhooks/store_order_transaction_updated.yml
Labels: awaiting-peer-review

#1363 DEVDOCS-4791: [update] gift certificates endpoint
  reference/marketing.v2.yml
Labels: awaiting-peer-review
