Repository bigcommerce/api-specs, pull requests merged in 2023-12, with the labels that each got.

#1538 DEVDOCS-5671 [revise] Checkout Storefront, Update gift wrapping around CRUD
  reference/carts.sf.yml
  reference/checkouts.sf.yml
Labels: from-engineering

#1514 (no ticket): [update] Several docs, copyedits
  reference/catalog/product-variants_catalog.v3.yml
  reference/pages.v3.yml
  reference/price_lists.v3.yml
  reference/shipping.v2.yml
  reference/webhooks.v3.yml
Labels: merge-before-migration

#1391 Update shipping_provider.yml
  reference/shipping_provider.yml
Labels: merge-before-migration

#1494 (no ticket): [update] Widgets, change widget datetime string format to one that exists
  reference/widgets.v3.yml
Labels: merge-before-migration

#1535 DEVDOCS-5662: [new] Channels API, add requirements for channel name
  reference/channels.v3.yml
Labels: awaiting-css-cue, merge-before-migration

#1233 (no ticket): [external] Webhooks, fix header field to indicate support for custom key-value pairs
  reference/webhooks.v3.yml
Labels: do not merge, external

#1241 (no ticket): [external] Webhooks, create webhook_Put schema without required fields
  reference/webhooks.v3.yml
Labels: do not merge, external
