Repository bigcommerce/api-specs, pull requests merged in 2023-08, with the labels that each got.

#1397 DEVDOCS-5166: [update] Pricing, Get Prices Batch, include tax_discount_amount array to bath response
  reference/pricing.sf.yml
Labels: do not merge, awaiting-pe-sme-review, awaiting-peer-review

#1400 DEVDOCS-5234: [revise] Customers V2, Remove 'id' from Update a Customer group parameters
  reference/customers.v2.yml
Labels: awaiting-peer-review

#1402 DEVDOCS-5059 [revise] OrderSF, add `brand` to `lineItems`
  reference/orders.sf.yml
Labels: awaiting-peer-review

#1405 DEVDOCS-5097: [update] Catalog, Products, include list of sub resources for `include` field.
  reference/catalog/products_catalog.v3.yml
Labels: awaiting-peer-review

#1406 DEVDOCS-5257: [revise] Orders V2, Update example for Create product with variants
  reference/orders.v2.oas2.yml
Labels: awaiting-peer-review

#1413 DEVDOCS-4861: [Update] Added 409 error code
  reference/catalog/category-trees_catalog.v3.yml
Labels: do not merge, awaiting-peer-review

#1414 Revert "DEVDOCS-4861: [Update] Added 409 error code"
  reference/catalog/category-trees_catalog.v3.yml
Labels: do not merge

#1415 [DEVDOCS-5304]: [revise] CustomersV2, add filter parameters to Customer Groups
  reference/customers.v2.yml
Labels: awaiting-peer-review

#1409 DEVDOCS-5241: [update] Add tokenized card
  reference/payments/process_payments.yml
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1426 DEVDOCS-4569: [update] Pages V3, change response body datatype
  reference/pages.v3.yml
Labels: awaiting-peer-review

#1427 DEVDOCS-5072: [update] external_id and external_order_id
  reference/orders.v2.oas2.yml
Labels: awaiting-peer-review
