Repository bigcommerce/api-specs, pull requests merged in 2023-10, with the labels that each got.

#1482 [DEVDOCS-5478]: [Revise] Pricelists, Update rate limits GET/PUT/DELETE /{currency_code}
  reference/price_lists.v3.yml
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1483 DEVDOCS-5476: [update] Add-a-rate-limit-to-PUT-price-list-assignments
  reference/price_lists.v3.yml
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1480 DEVDOCS-5385: [update] removed pagination > links object
  reference/themes.v3.yml
Labels: awaiting-peer-review

#1485 DEVDOCS-5359: [update]Added originalPrice
  reference/checkouts.sf.yml
Labels: awaiting-peer-review

#1484 DEVDOCS-5447:[update]Update schema and example for Upsert Category Tr…
  reference/catalog/category-trees_catalog.v3.yml
Labels: awaiting-peer-review

#1493 DEVDOCS-5491: [update] add status
  reference/webhooks.v3.yml
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1498 DEVDOCS-5493: [update] add cleanup policy
  reference/webhooks.v3.yml
Labels: awaiting-peer-review

#1499 DEVDOCS-5469: [update] update url object
  reference/catalog/category-trees_catalog.v3.yml
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1504 SELFDEV-370: [update] Replace links
  reference/abandoned_cart_emails.v3.yaml
  reference/abandoned_carts.v3.yml
  reference/carts.sf.yml
  reference/carts.v3.yml
  reference/catalog/brands_catalog.v3.yml
  reference/catalog/categories_catalog.v3.yml
  reference/catalog/category-trees_catalog.v3.yml
  reference/catalog/product-modifiers_catalog.v3.yml
  reference/catalog/product-variant-options_catalog.v3.yml
  reference/catalog/product-variants_catalog.v3.yml
  reference/catalog/products_catalog.v3.yml
  reference/channels.v3.yml
  reference/checkouts.sf.yml
  reference/checkouts.v3.yml
  reference/consent.sf.yml
  reference/currencies.v2.yml
  reference/current_customer.yml
  reference/custom-template-associations.v3.yml
  reference/customer_login.yml
  reference/customers.sf.yml
  reference/customers.v2.yml
  reference/customers.v3.yml
  reference/email_templates.v3.yml
  reference/form_fields.sf.yml
  reference/geography.v2.yml
  reference/marketing.v2.yml
  reference/orders.sf.yml
  reference/orders.v2.oas2.yml
  reference/orders.v3.yml
  reference/payments/accepted-methods_payments.v3.yml
  reference/payments/access-tokens_payments.v3.yml
  reference/payments/methods_payments.v2.yml
  reference/payments/process_payments.yml
  reference/price_lists.v3.yml
  reference/pricing.sf.yml
  reference/redirects.v3.yml
  reference/scripts.v3.yml
  reference/settings.v3.yml
  reference/shipping.v2.yml
  reference/shipping.v3.yml
  reference/shipping_provider.yml
  reference/sites.v3.yml
  reference/store_content.v2.yml
  reference/store_information.v2.yml
  reference/store_logs.v3.yml
  reference/storefront_tokens.v3.yml
  reference/subscribers.v3.yml
  reference/subscriptions.sf.yml
  reference/tax.v3.yml
  reference/tax_classes.v2.yml
  reference/tax_properties.v3.yml
  reference/tax_provider.yml
  reference/tax_rates_zones.v3.yml
  reference/tax_settings.v3.yml
  reference/themes.v3.yml
  reference/webhooks.v3.yml
  reference/widgets.v3.yml
  reference/wishlists.v3.yml
Labels: do not merge

#1506 DEVDOCS-5572: [Update] add notes about concurrent requests
  reference/carts.sf.yml
  reference/carts.v3.yml
  reference/checkouts.sf.yml
  reference/checkouts.v3.yml
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1507 DEVDOCS-5109: [update] update batch limit
  reference/catalog/products_catalog.v3.yml
Labels: awaiting-peer-review
