Repository bigcommerce/api-specs, pull requests merged in 2023-09, with the labels that each got.

#1455 DEVDOCS-5362: [revise] Ordersv2, Update tracking_link details
  reference/orders.v2.oas2.yml
Labels: awaiting-peer-review

#1457 DEVDOCS-5420: [new] Expose discounted_total_inc_tax on the orders v2 api
  reference/orders.v2.oas2.yml
Labels: ready-to-merge

#1432 DEVDOCS-5146: [update] update cost_price fields
  reference/orders.v2.oas2.yml
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1428 DEVDOCS-5057: [update] Theme job
  reference/themes.v3.yml
Labels: awaiting-pe-sme-review, awaiting-peer-review

#1430 DEVDOCS-5395: [update] change object to array
  reference/catalog/categories_catalog.v3.yml
Labels: awaiting-pe-sme-review

#1454 bugfix: remove duplicate video id param on product video endpoint
  reference/catalog/products_catalog.v3.yml
Labels: ready-to-merge

#1453 bugfix: remove duplicate uuid param on theme configuration endpoint.
  reference/themes.v3.yml
Labels: ready-to-merge

#1452 bugfix: remove duplicate category id param on category sort order endpoint
  reference/catalog/categories_catalog.v3.yml
Labels: ready-to-merge

#1451 bugfix: review duplicate review id param on product reviews endpoint
  reference/catalog/products_catalog.v3.yml
Labels: ready-to-merge

#1450 bugfix: remove duplicate variant_id param from product variants endpoint
  reference/catalog/product-variants_catalog.v3.yml
Labels: ready-to-merge

#1449 bugfix: remove product variant options option_id param
  reference/catalog/product-variant-options_catalog.v3.yml
Labels: ready-to-merge

#1448 bugfix: remove duplicate product modifier id param
  reference/catalog/product-modifiers_catalog.v3.yml
Labels: ready-to-merge

#1429 STRF-11160: [new] Redirects V3, add Import-Export
  reference/redirects.v3.yml
Labels: do not merge

#1477 DEVDOCS-5285: [update] tree_id is not required for updating categories
  reference/catalog/category-trees_catalog.v3.yml
Labels: awaiting-peer-review
